
package com.apostit.client;

import com.google.gwt.i18n.client.Constants;
import com.google.gwt.i18n.client.LocalizableResource.DefaultLocale;
import com.google.gwt.i18n.client.LocalizableResource.Key;
import com.google.gwt.i18n.client.Messages;

@DefaultLocale("en")
public interface Messages extends Constants {
    @Key("appTitle")
    String appTitle();
    
    @Key("category")
    String category();
    
    @Key("fromCountryLabel")
    String fromCountryLabel();
    
    @Key("fromSizeLabel")
    String fromSizeLabel();
    
    @Key("toCountryLabel")
    String toCountryLabel();
    
    // ... other methods will be auto-generated by GWT from your properties file
}
